### PR TITLE
 Comprehensive connection testing tool, fixes #13

### LINKED ISSUE #13: Add quick connection test tool
Currently, the Opencast API configuration has to be done blindly on /admin/settings.php?section=tool_opencast. If the settings aren't entered fully correctly (see #11 at least for an enhancement to add better descriptions and validation), you won't see that the connection is broken until you try to upload a video with block_opencast or try to download or try to fetch a video with repository_opencast.

I would propose to add a quick connection test tool to  /admin/settings.php?section=tool_opencast to answer the questions:
* Is there an Opencast instance running on the configured URL?
* Can Moodle connect to Opencast with the configured credentials?

Referencing https://tracker.moodle.org/browse/MDL-65053 as this might help (at least if it's implemented before this issue here is tackled)

### PR DESCRIPTION
**Pull request by ferishili**
#13

### CODE REVIEW

**Comment by ferishili** [comment]
Hi @TamaraGunkel,
the proposed connection testing tool is designed to test the connection as a separate tool and when the admin saves the inputs in admin page!
Please take a look and give me your feedback. 
Thanks in advance.

File: lib.php [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+ * Helperfunction to validate given credentials for the Opencast API URL.
+ * It uses curl with Authorization header.
+ *
+ * @param bool $redirect: When true a redirect action to admin page will occure upon failure. Otherwise, an html tag as string will be returned.
+ * 
+ * @return string in case the function is called through connection test tool an html tag as string will be returned.
+ */
+function tool_opencast_test_connection_with_credentials($redirect = true) {
+    // Initialize cURL.
+    $curl = new \curl();
```
Comment (TamaraGunkel) [inline lib.php:104]: Why didn't you extend the `api` class instead of reimplementing the curl connection?

File: testtool.php [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+
+/**
+ * 
+ * @package    tool_opencast
+ * @copyright  2021 Farbod Zamani Boroujeni, ELAN e.V.
+ * @author     Farbod Zamani Boroujeni <zamani@elan-ev.de>
+ * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
+ */
+
+require_once(__DIR__ . '/../../config.php');
```
Comment (TamaraGunkel) [inline testtool.php:25]: Does that work for you?
I think it should be `__DIR__ . '/../../config.php'` because we're in the `admin/tool/opencast` directory.

**Review by TamaraGunkel — CHANGES_REQUESTED** [review]
Hey, 
thanks for your PR.
I added some comments so that you can improve it.
Also, I would have appreciated an AJAX solution to improve the user experience. 
Currently, users have to leave the admin settings page to check the connection and the check is conducted with the already saved settings.
It would be more intuitive if you have a button that opens a Popup showing if the connection was successful or not. The check should use the entered connection details (even if not saved yet) because you would usually want to test the connection *before* saving it. I think Alex had something similar in mind because he linked the issue with the popup setting (which isn't available yet but there are other ways to implement it).
What do you think of that?

**Comment by ferishili** [comment]
Thanks for the review, will update it as soon as the other issue is done!

File: testtool.php (hunk 2 above)
Comment (ferishili) [reply testtool.php:25]: Oh my bad, sorry, I forgot to add the extra tool dir in my working env.

**Comment by ferishili** [comment]
Hi @TamaraGunkel,
Please take a look at the latest commit, which contains Ajax call and modal. 
Thanks in advance.

**Comment by TamaraGunkel** [comment]
Thanks a lot for the improvements!
